language: c
compiler:
  - gcc
  - clang
before_script:
  - sudo apt-get update -qq -y
  - sudo apt-get install check -y
  - sudo ./misc/install-libuv.sh
  - make clean
  - make
script: make test
branches:
  only:
    - master
    - develop
